### ISSUE TITLE
Main body STL

### ISSUE THREAD

**Issue by Bigood-f3k** [bigtreetech/EBB#104]
Hello, the main body STL does not work. Could you update it please?

**Comment by yoeywire** [comment]
Same for me, the STL file seems to be corrupted.

**Comment by sboehle** [comment]
Looks like the file was only renamed. Here the link to the previous one:
https://github.com/bigtreetech/EBB/blob/35baceb5cac23f437ba8bebc3f8c5f33144fc09a/EBB%20SB2240_2209%20CAN/STL/Main_Body_V1.2.stl

**Comment by DicyRoll** [comment]
It seems to me that the new file is literally empty, something went wrong there.

**Comment by DicyRoll** [comment]
@Bigood-f3k the file has been fixed (50a078d), I think you can close the issue.

**Comment by Bigood-f3k** [comment]
Great thanks!
