### ISSUE TITLE
MCU Temperatur reading via CAN

### ISSUE THREAD

**Issue by Aergernis** [bigtreetech/EBB#126]
Hi,
is it possible to read the MCU temp from EBB36 via CAN bus? If so how? Couldn't find anything in the docs.

**Comment by oMTEo** [comment]
Maybe this helps :

[temperature_fan EBB36]
sensor_type: temperature_mcu
sensor_mcu: EBB
pin: EBB:FAN2
off_below: 0.3
control: watermark
max_delta: 5
min_temp: 0
max_temp: 80
target_temp: 35.0
min_speed: 0.0
max_speed: 0.7 ## Fan throttled

**Comment by Aergernis** [comment]
Thanks for hint. It's working with

```
[temperature_sensor EBB36]
sensor_type: temperature_mcu
sensor_mcu: EBB36
```
