### ISSUE TITLE
EBB36 + CAN hub?

### ISSUE THREAD

**Issue by Breakage20** [bigtreetech/EBB#13]
Hey,
I've got a question, is it possible to use EBB36 with can hub supplied with Hermit Crab? I wanted to test it but something in my brain tells me that i will fry the board. The question is, is it possible to supply 24V and can comunication via USB C like in hermit crab?

**Comment by eightheads** [comment]
No, you cannot use the USB-C from the Hermit Crab CAN with the EBB boards.
