### ISSUE TITLE
Please add BIGTREETECH EBB SB2209 USB V1.0_SCH.pdf

### ISSUE THREAD

**Issue by thedemoncat** [bigtreetech/EBB#140]
Good afternoon!
Please add an electrical diagram for EBB SB2209_USB
Thanks!

**Comment by thedemoncat** [comment]
@looxonline Can you help me with the scheme? My controller has problems over the USB line. Strong heating of the stabilizer in the sot23 housing near the USB port. I really need a diagram and the name of the elements.
Thank you in advance and I hope for your help

**Comment by thedemoncat** [comment]
Tell me, what does this symbol on the diagram mean?
![image](https://github.com/user-attachments/assets/afbfc988-fad8-4c49-8c4e-188542dde873)

**Comment by bigtreetech** [comment]
Differential pair with impedance matching.

**Comment by DRCRecoveryData** [comment]
> I've dealt with the problem on the board a bit. Due to a short circuit, the USB FE1.1S controller burned out, as well as the U6 - LPW5209AB5F-21 key.
> 
> The main problem is not high-quality pins for connecting the switching board. They break off and cause a short circuit

How you solve it
