### ISSUE TITLE
Grounding the extruder motor via the board mounting screw?

### ISSUE THREAD

**Issue by GaryBoone** [bigtreetech/EBB#145]
The EBB SB2209 USB manual suggests grounding the extruder motor with a wire included in the box that runs from the motor to a JST connector on any free ground pin. However, I see that the mounting holes in the middle of the toolhead PCB are both plated through-holes. Presumably, these are both connected to ground. It looks like there's room for a spade terminal under the mounting M3x8 screw. Is that an acceptable grounding connection?

**Comment by bigtreetech** [comment]
I believe that they are isolated on that board so they will not work.
